asdf:
	javadoc -private -d . ../../Naamakahvi-parent/client/src/main/java/naamakahvi/naamakahviclient/*.java \
../../Naamakahvi-parent/android-ui/src/naamakahvi/android/utils/*.java \
../../Naamakahvi-parent/android-ui/src/naamakahvi/android/components/*.java \
../../Naamakahvi-parent/android-ui/src/naamakahvi/android/*.java ../../Naamakahvi-parent/swingui/src/main/java/naamakahvi/swingui/*.java


