asdf:
	javadoc -d . ../../Naamakahvi-parent/client/src/main/java/naamakahvi/naamakahviclient/*.java ../../Naamakahvi-parent/android-ui/src/naamakahvi/android/*.java ../../Naamakahvi-parent/swingui/src/main/java/naamakahvi/swingui/*.java


